// @see: https://cz-git.qbenben.com/zh/guide
/** @type {import('cz-git').UserConfig} */

module.exports = {
    ignores: [(commit) => commit.includes('init')],
    extends: ['@commitlint/config-conventional'],
    rules: {
      // @see: https://commitlint.js.org/#/reference-rules
      'body-leading-blank': [2, 'always'],
      'footer-leading-blank': [1, 'always'],
      'header-max-length': [2, 'always', 108],
      'subject-empty': [2, 'never'],
      'type-empty': [2, 'never'],
      'subject-case': [0],
      'type-enum': [
        2,
        'always',
        [
          'feat',
          'fix',
          'docs',
          'style',
          'refactor',
          'perf',
          'test',
          'build',
          'ci',
          'chore',
          'revert',
          'wip',
          'workflow',
          'types',
          'release',
        ],
      ],
    },
    prompt: {
      messages: {
        type: '選擇你要提交的類型 :',
        scope: '選擇一個提交範圍（可選）:',
        customScope: '請輸入自定義的提交範圍 :',
        subject: '填寫簡短精煉的變更描述 :\n',
        body: '填寫更加詳細的變更描述（可選）。使用 "|" 換行 :\n',
        breaking: '列舉非兼容性重大的變更（可選）。使用 "|" 換行 :\n',
        footerPrefixsSelect: '選擇關聯issue前綴（可選）:',
        customFooterPrefixs: '輸入自定義issue前綴 :',
        footer: '列舉關聯issue (可選) 例如: #31, #I3244 :\n',
        confirmCommit: '是否提交或修改commit ?',
      },
      types: [
        { value: 'feat', name: 'feat: 新增功能' },
        { value: 'fix', name: 'fix: 修復缺陷' },
        { value: 'docs', name: 'docs: 文檔變更' },
        { value: 'style', name: 'style: 代碼格式（不影響功能，例如空格、分號等格式修正）' },
        { value: 'refactor', name: 'refactor: 代碼重構（不包括 bug 修復、功能新增）' },
        { value: 'perf', name: 'perf: 性能優化' },
        { value: 'test', name: 'test: 添加疏漏測試或已有測試改動' },
        { value: 'build', name: 'build: 構建流程、外部依賴變更（如昇級 npm 包、修改 webpack 配置等）' },
        { value: 'ci', name: 'ci: 修改 CI 配置、腳本' },
        { value: 'chore', name: 'chore: 回滾 commit' },
        { value: 'revert', name: 'revert: 對構建過程或輔助工具和庫的更改（不影響源文件、測試用例）' },
      ],
      useEmoji: true,
      themeColorCode: '',
      scopes: [],
      allowCustomScopes: true,
      allowEmptyScopes: true,
      customScopesAlign: 'bottom',
      customScopesAlias: 'custom',
      emptyScopesAlias: 'empty',
      upperCaseSubject: false,
      allowBreakingChanges: ['feat', 'fix'],
      breaklineNumber: 100,
      breaklineChar: '|',
      skipQuestions: [],
      issuePrefixs: [{ value: 'closed', name: 'closed:   ISSUES has been processed' }],
      customIssuePrefixsAlign: 'top',
      emptyIssuePrefixsAlias: 'skip',
      customIssuePrefixsAlias: 'custom',
      allowCustomIssuePrefixs: true,
      allowEmptyIssuePrefixs: true,
      confirmColorize: true,
      maxHeaderLength: Infinity,
      maxSubjectLength: Infinity,
      minSubjectLength: 0,
      scopeOverrides: undefined,
      defaultBody: '',
      defaultIssues: '',
      defaultScope: '',
      defaultSubject: '',
    },
  };